var p2pData = [  
   {  
      "roi":0.57,
      "pathCount":8666112,
      "impressionPerNode":2.5,
      "conversionRate":0.038,
      "pathId":1,
      "nodes":[  
         {  
            "pathId":1,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":1,
            "time":0.0,
            "label":"NYTimes"
         },
         {  
            "pathId":1,
            "time":0.0,
            "label":"MSN"
         },
         {  
            "pathId":1,
            "time":0.0,
            "label":""
         },
         {  
            "pathId":1,
            "time":0.0,
            "label":"eBay"
         }
      ],
      "effectiveness":1.4
   },
   {  
      "roi":0.49,
      "pathCount":51322,
      "impressionPerNode":6.91,
      "conversionRate":0.001,
      "pathId":2,
      "nodes":[  
         {  
            "pathId":2,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":2,
            "time":3.8,
            "label":"Yahoo"
         },
         {  
            "pathId":2,
            "time":9.6,
            "label":"ESPN2"
         },
         {  
            "pathId":2,
            "time":21.5,
            "label":"Buzzfeed"
         },
         {  
            "pathId":2,
            "time":22.5,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.19
   },
   {  
      "roi":2.45,
      "pathCount":10590,
      "impressionPerNode":7.13,
      "conversionRate":0.024,
      "pathId":3,
      "nodes":[  
         {  
            "pathId":3,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":3,
            "time":24.1,
            "label":"MSN"
         },
         {  
            "pathId":3,
            "time":25.6,
            "label":""
         }
      ],
      "effectiveness":0.65
   },
   {  
      "roi":0.22,
      "pathCount":745583,
      "impressionPerNode":3.87,
      "conversionRate":0.034,
      "pathId":4,
      "nodes":[  
         {  
            "pathId":4,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":4,
            "time":15.7,
            "label":"eBay"
         },
         {  
            "pathId":4,
            "time":27.4,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.28
   },
   {  
      "roi":0.13,
      "pathCount":625602,
      "impressionPerNode":7.11,
      "conversionRate":0.016,
      "pathId":5,
      "nodes":[  
         {  
            "pathId":5,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":5,
            "time":29.6,
            "label":"MSN"
         },
         {  
            "pathId":5,
            "time":28.6,
            "label":"MSN"
         },
         {  
            "pathId":5,
            "time":26.6,
            "label":"MSN"
         },
         {  
            "pathId":5,
            "time":26.8,
            "label":"Buzzfeed"
         },
         {  
            "pathId":5,
            "time":26.8,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.97
   },
   {  
      "roi":2.3,
      "pathCount":389772,
      "impressionPerNode":5.08,
      "conversionRate":0.015,
      "pathId":6,
      "nodes":[  
         {  
            "pathId":6,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":6,
            "time":19.4,
            "label":"ESPN2"
         },
         {  
            "pathId":6,
            "time":27.8,
            "label":""
         },
         {  
            "pathId":6,
            "time":26.3,
            "label":"Yahoo"
         },
         {  
            "pathId":6,
            "time":27.1,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.81
   },
   {  
      "roi":0.16,
      "pathCount":1933957,
      "impressionPerNode":6.71,
      "conversionRate":0.033,
      "pathId":7,
      "nodes":[  
         {  
            "pathId":7,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.46
   },
   {  
      "roi":0.31,
      "pathCount":5997373,
      "impressionPerNode":1.83,
      "conversionRate":0.063,
      "pathId":8,
      "nodes":[  
         {  
            "pathId":8,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":8,
            "time":85.4,
            "label":"Buzzfeed"
         },
         {  
            "pathId":8,
            "time":-67.6,
            "label":"MSN"
         }
      ],
      "effectiveness":0.67
   },
   {  
      "roi":0.07,
      "pathCount":307949,
      "impressionPerNode":4.73,
      "conversionRate":0.002,
      "pathId":9,
      "nodes":[  
         {  
            "pathId":9,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":9,
            "time":47.0,
            "label":"YouTube"
         },
         {  
            "pathId":9,
            "time":13.1,
            "label":"eBay"
         },
         {  
            "pathId":9,
            "time":58.5,
            "label":"YouTube"
         },
         {  
            "pathId":9,
            "time":-44.2,
            "label":""
         },
         {  
            "pathId":9,
            "time":183.1,
            "label":"Buzzfeed"
         },
         {  
            "pathId":9,
            "time":-299.1,
            "label":"MSN"
         }
      ],
      "effectiveness":0.82
   },
   {  
      "roi":0.93,
      "pathCount":3771502,
      "impressionPerNode":5.68,
      "conversionRate":0.091,
      "pathId":10,
      "nodes":[  
         {  
            "pathId":10,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":10,
            "time":79.8,
            "label":"MSN"
         },
         {  
            "pathId":10,
            "time":-31.7,
            "label":"NYTimes"
         },
         {  
            "pathId":10,
            "time":255.2,
            "label":"YouTube"
         },
         {  
            "pathId":10,
            "time":-342.2,
            "label":"Buzzfeed"
         },
         {  
            "pathId":10,
            "time":1325.4,
            "label":"eBay"
         }
      ],
      "effectiveness":0.71
   },
   {  
      "roi":1.2,
      "pathCount":1994306,
      "impressionPerNode":2.47,
      "conversionRate":0.009,
      "pathId":11,
      "nodes":[  
         {  
            "pathId":11,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":11,
            "time":105.2,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.23
   },
   {  
      "roi":0.17,
      "pathCount":2909716,
      "impressionPerNode":6.36,
      "conversionRate":0.013,
      "pathId":12,
      "nodes":[  
         {  
            "pathId":12,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.84
   },
   {  
      "roi":2.87,
      "pathCount":552931,
      "impressionPerNode":7.56,
      "conversionRate":0.026,
      "pathId":13,
      "nodes":[  
         {  
            "pathId":13,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":13,
            "time":57.6,
            "label":"YouTube"
         },
         {  
            "pathId":13,
            "time":-3.7,
            "label":"Buzzfeed"
         },
         {  
            "pathId":13,
            "time":165.5,
            "label":""
         }
      ],
      "effectiveness":1.02
   },
   {  
      "roi":2.4,
      "pathCount":1221605,
      "impressionPerNode":1.32,
      "conversionRate":0.006,
      "pathId":14,
      "nodes":[  
         {  
            "pathId":14,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":14,
            "time":133.2,
            "label":"MSN"
         },
         {  
            "pathId":14,
            "time":-124.0,
            "label":"YouTube"
         },
         {  
            "pathId":14,
            "time":462.0,
            "label":"YouTube"
         },
         {  
            "pathId":14,
            "time":-874.5,
            "label":"YouTube"
         },
         {  
            "pathId":14,
            "time":731.4,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.52
   },
   {  
      "roi":0.64,
      "pathCount":8056837,
      "impressionPerNode":7.28,
      "conversionRate":0.018,
      "pathId":15,
      "nodes":[  
         {  
            "pathId":15,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":15,
            "time":117.7,
            "label":"eBay"
         },
         {  
            "pathId":15,
            "time":-274.9,
            "label":"ESPN2"
         },
         {  
            "pathId":15,
            "time":1650.0,
            "label":"eBay"
         },
         {  
            "pathId":15,
            "time":-6128.4,
            "label":"ESPN2"
         },
         {  
            "pathId":15,
            "time":12428.1,
            "label":"Buzzfeed"
         },
         {  
            "pathId":15,
            "time":2617.7,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.1
   },
   {  
      "roi":0.08,
      "pathCount":1325192,
      "impressionPerNode":4.2,
      "conversionRate":0.005,
      "pathId":16,
      "nodes":[  
         {  
            "pathId":16,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":16,
            "time":5.2,
            "label":"eBay"
         }
      ],
      "effectiveness":1.73
   },
   {  
      "roi":0.79,
      "pathCount":4326675,
      "impressionPerNode":3.53,
      "conversionRate":0.007,
      "pathId":17,
      "nodes":[  
         {  
            "pathId":17,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":17,
            "time":112.8,
            "label":"NYTimes"
         },
         {  
            "pathId":17,
            "time":-279.6,
            "label":"NYTimes"
         },
         {  
            "pathId":17,
            "time":555.8,
            "label":""
         }
      ],
      "effectiveness":0.07
   },
   {  
      "roi":0.46,
      "pathCount":4437532,
      "impressionPerNode":3.73,
      "conversionRate":0.021,
      "pathId":18,
      "nodes":[  
         {  
            "pathId":18,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":18,
            "time":24.6,
            "label":"MSN"
         },
         {  
            "pathId":18,
            "time":24.8,
            "label":"Yahoo"
         },
         {  
            "pathId":18,
            "time":29.9,
            "label":"YouTube"
         },
         {  
            "pathId":18,
            "time":15.2,
            "label":"Yahoo"
         },
         {  
            "pathId":18,
            "time":74.0,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.05
   },
   {  
      "roi":0.01,
      "pathCount":4115031,
      "impressionPerNode":7.6,
      "conversionRate":0.041,
      "pathId":19,
      "nodes":[  
         {  
            "pathId":19,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":19,
            "time":38.2,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.07
   },
   {  
      "roi":1.43,
      "pathCount":345557,
      "impressionPerNode":7.44,
      "conversionRate":0.002,
      "pathId":20,
      "nodes":[  
         {  
            "pathId":20,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":20,
            "time":211.6,
            "label":"NYTimes"
         },
         {  
            "pathId":20,
            "time":-911.1,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.45
   },
   {  
      "roi":2.41,
      "pathCount":8361171,
      "impressionPerNode":5.29,
      "conversionRate":0.013,
      "pathId":21,
      "nodes":[  
         {  
            "pathId":21,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.27
   },
   {  
      "roi":0.05,
      "pathCount":377263,
      "impressionPerNode":4.65,
      "conversionRate":0.01,
      "pathId":22,
      "nodes":[  
         {  
            "pathId":22,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":22,
            "time":271.0,
            "label":"Yahoo"
         },
         {  
            "pathId":22,
            "time":-1107.0,
            "label":"Yahoo"
         },
         {  
            "pathId":22,
            "time":5280.3,
            "label":"eBay"
         }
      ],
      "effectiveness":0.12
   },
   {  
      "roi":2.9,
      "pathCount":2153476,
      "impressionPerNode":3.64,
      "conversionRate":0.055,
      "pathId":23,
      "nodes":[  
         {  
            "pathId":23,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":23,
            "time":33.0,
            "label":"MSN"
         },
         {  
            "pathId":23,
            "time":-32.1,
            "label":"Buzzfeed"
         },
         {  
            "pathId":23,
            "time":565.5,
            "label":""
         },
         {  
            "pathId":23,
            "time":369.2,
            "label":"MSN"
         },
         {  
            "pathId":23,
            "time":-2180.3,
            "label":"eBay"
         },
         {  
            "pathId":23,
            "time":9582.1,
            "label":"YouTube"
         },
         {  
            "pathId":23,
            "time":-87590.5,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.77
   },
   {  
      "roi":1.16,
      "pathCount":2277384,
      "impressionPerNode":5.39,
      "conversionRate":0.023,
      "pathId":24,
      "nodes":[  
         {  
            "pathId":24,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":24,
            "time":21.4,
            "label":"ESPN2"
         }
      ],
      "effectiveness":2.43
   },
   {  
      "roi":0.5,
      "pathCount":504618,
      "impressionPerNode":6.38,
      "conversionRate":0.001,
      "pathId":25,
      "nodes":[  
         {  
            "pathId":25,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":25,
            "time":163.4,
            "label":"Yahoo"
         },
         {  
            "pathId":25,
            "time":-1468.0,
            "label":"Buzzfeed"
         },
         {  
            "pathId":25,
            "time":5409.6,
            "label":"Yahoo"
         }
      ],
      "effectiveness":0.4
   },
   {  
      "roi":0.28,
      "pathCount":1474638,
      "impressionPerNode":3.19,
      "conversionRate":0.002,
      "pathId":26,
      "nodes":[  
         {  
            "pathId":26,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":26,
            "time":140.2,
            "label":"MSN"
         }
      ],
      "effectiveness":1.01
   },
   {  
      "roi":0.22,
      "pathCount":4013524,
      "impressionPerNode":6.77,
      "conversionRate":0.05,
      "pathId":27,
      "nodes":[  
         {  
            "pathId":27,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":27,
            "time":164.8,
            "label":"Buzzfeed"
         },
         {  
            "pathId":27,
            "time":-897.7,
            "label":""
         },
         {  
            "pathId":27,
            "time":1919.6,
            "label":"MSN"
         },
         {  
            "pathId":27,
            "time":-7133.2,
            "label":"YouTube"
         },
         {  
            "pathId":27,
            "time":67983.2,
            "label":""
         },
         {  
            "pathId":27,
            "time":-509442.6,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.62
   },
   {  
      "roi":2.68,
      "pathCount":639829,
      "impressionPerNode":6.78,
      "conversionRate":0.071,
      "pathId":28,
      "nodes":[  
         {  
            "pathId":28,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":28,
            "time":39.1,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.7
   },
   {  
      "roi":0.3,
      "pathCount":7938313,
      "impressionPerNode":1.99,
      "conversionRate":0.013,
      "pathId":29,
      "nodes":[  
         {  
            "pathId":29,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":29,
            "time":280.6,
            "label":"YouTube"
         },
         {  
            "pathId":29,
            "time":-880.7,
            "label":"Yahoo"
         },
         {  
            "pathId":29,
            "time":3595.2,
            "label":"NYTimes"
         }
      ],
      "effectiveness":1.06
   },
   {  
      "roi":0.59,
      "pathCount":5104096,
      "impressionPerNode":5.06,
      "conversionRate":0.042,
      "pathId":30,
      "nodes":[  
         {  
            "pathId":30,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.21
   },
   {  
      "roi":1.33,
      "pathCount":3056364,
      "impressionPerNode":7.47,
      "conversionRate":0.007,
      "pathId":31,
      "nodes":[  
         {  
            "pathId":31,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.12
   },
   {  
      "roi":0.26,
      "pathCount":380939,
      "impressionPerNode":3.72,
      "conversionRate":0.023,
      "pathId":32,
      "nodes":[  
         {  
            "pathId":32,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":32,
            "time":293.7,
            "label":"YouTube"
         },
         {  
            "pathId":32,
            "time":-3790.9,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.92
   },
   {  
      "roi":0.42,
      "pathCount":3193318,
      "impressionPerNode":7.3,
      "conversionRate":0.066,
      "pathId":33,
      "nodes":[  
         {  
            "pathId":33,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":33,
            "time":298.8,
            "label":"eBay"
         }
      ],
      "effectiveness":0.22
   },
   {  
      "roi":0.04,
      "pathCount":1925226,
      "impressionPerNode":3.73,
      "conversionRate":0.034,
      "pathId":34,
      "nodes":[  
         {  
            "pathId":34,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":34,
            "time":158.1,
            "label":"eBay"
         },
         {  
            "pathId":34,
            "time":-1006.1,
            "label":"Buzzfeed"
         },
         {  
            "pathId":34,
            "time":11933.1,
            "label":"YouTube"
         },
         {  
            "pathId":34,
            "time":-138370.9,
            "label":"eBay"
         },
         {  
            "pathId":34,
            "time":1707176.3,
            "label":"MSN"
         }
      ],
      "effectiveness":0.17
   },
   {  
      "roi":1.98,
      "pathCount":8511581,
      "impressionPerNode":4.44,
      "conversionRate":0.012,
      "pathId":35,
      "nodes":[  
         {  
            "pathId":35,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":35,
            "time":174.7,
            "label":"eBay"
         },
         {  
            "pathId":35,
            "time":-674.6,
            "label":"MSN"
         },
         {  
            "pathId":35,
            "time":5583.8,
            "label":"Buzzfeed"
         },
         {  
            "pathId":35,
            "time":-38792.3,
            "label":"NYTimes"
         },
         {  
            "pathId":35,
            "time":295992.9,
            "label":"ESPN2"
         },
         {  
            "pathId":35,
            "time":-3236969.2,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.26
   },
   {  
      "roi":1.88,
      "pathCount":3015069,
      "impressionPerNode":4.01,
      "conversionRate":0.0,
      "pathId":36,
      "nodes":[  
         {  
            "pathId":36,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":36,
            "time":79.3,
            "label":"YouTube"
         },
         {  
            "pathId":36,
            "time":-501.4,
            "label":"Yahoo"
         },
         {  
            "pathId":36,
            "time":393.4,
            "label":"Yahoo"
         },
         {  
            "pathId":36,
            "time":-1983.5,
            "label":""
         }
      ],
      "effectiveness":1.76
   },
   {  
      "roi":0.51,
      "pathCount":2483718,
      "impressionPerNode":7.81,
      "conversionRate":0.01,
      "pathId":37,
      "nodes":[  
         {  
            "pathId":37,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":37,
            "time":311.0,
            "label":"Yahoo"
         },
         {  
            "pathId":37,
            "time":-1314.7,
            "label":"MSN"
         }
      ],
      "effectiveness":0.21
   },
   {  
      "roi":1.08,
      "pathCount":478582,
      "impressionPerNode":4.76,
      "conversionRate":0.004,
      "pathId":38,
      "nodes":[  
         {  
            "pathId":38,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":38,
            "time":69.2,
            "label":"YouTube"
         },
         {  
            "pathId":38,
            "time":-665.6,
            "label":"ESPN2"
         },
         {  
            "pathId":38,
            "time":856.4,
            "label":"MSN"
         },
         {  
            "pathId":38,
            "time":-11337.2,
            "label":"MSN"
         },
         {  
            "pathId":38,
            "time":45599.1,
            "label":"NYTimes"
         }
      ],
      "effectiveness":1.32
   },
   {  
      "roi":0.73,
      "pathCount":2804,
      "impressionPerNode":6.78,
      "conversionRate":0.032,
      "pathId":39,
      "nodes":[  
         {  
            "pathId":39,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":39,
            "time":77.5,
            "label":""
         },
         {  
            "pathId":39,
            "time":-130.9,
            "label":"YouTube"
         },
         {  
            "pathId":39,
            "time":1533.5,
            "label":"MSN"
         },
         {  
            "pathId":39,
            "time":-8860.6,
            "label":"YouTube"
         },
         {  
            "pathId":39,
            "time":89853.4,
            "label":"eBay"
         }
      ],
      "effectiveness":0.01
   },
   {  
      "roi":0.77,
      "pathCount":3601212,
      "impressionPerNode":5.7,
      "conversionRate":0.074,
      "pathId":40,
      "nodes":[  
         {  
            "pathId":40,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":40,
            "time":210.6,
            "label":"Yahoo"
         },
         {  
            "pathId":40,
            "time":-1037.6,
            "label":"MSN"
         },
         {  
            "pathId":40,
            "time":2487.2,
            "label":"eBay"
         },
         {  
            "pathId":40,
            "time":-40707.1,
            "label":"Yahoo"
         },
         {  
            "pathId":40,
            "time":554941.4,
            "label":"NYTimes"
         },
         {  
            "pathId":40,
            "time":-9674359.5,
            "label":""
         },
         {  
            "pathId":40,
            "time":-3019076.8,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":1.26
   },
   {  
      "roi":2.28,
      "pathCount":1306243,
      "impressionPerNode":5.4,
      "conversionRate":0.006,
      "pathId":41,
      "nodes":[  
         {  
            "pathId":41,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":41,
            "time":266.2,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.95
   },
   {  
      "roi":1.84,
      "pathCount":971743,
      "impressionPerNode":3.31,
      "conversionRate":0.018,
      "pathId":42,
      "nodes":[  
         {  
            "pathId":42,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":42,
            "time":560.9,
            "label":""
         },
         {  
            "pathId":42,
            "time":-2626.0,
            "label":"Buzzfeed"
         },
         {  
            "pathId":42,
            "time":12831.4,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.07
   },
   {  
      "roi":1.39,
      "pathCount":2247042,
      "impressionPerNode":6.12,
      "conversionRate":0.037,
      "pathId":43,
      "nodes":[  
         {  
            "pathId":43,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":43,
            "time":191.0,
            "label":"Yahoo"
         },
         {  
            "pathId":43,
            "time":-2474.5,
            "label":"Buzzfeed"
         },
         {  
            "pathId":43,
            "time":-533.3,
            "label":"MSN"
         },
         {  
            "pathId":43,
            "time":1653.8,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.78
   },
   {  
      "roi":0.39,
      "pathCount":1118488,
      "impressionPerNode":6.42,
      "conversionRate":0.017,
      "pathId":44,
      "nodes":[  
         {  
            "pathId":44,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":44,
            "time":578.0,
            "label":"Yahoo"
         },
         {  
            "pathId":44,
            "time":-5097.5,
            "label":"Yahoo"
         },
         {  
            "pathId":44,
            "time":72119.0,
            "label":"YouTube"
         },
         {  
            "pathId":44,
            "time":-968350.9,
            "label":"YouTube"
         },
         {  
            "pathId":44,
            "time":15107854.8,
            "label":"YouTube"
         },
         {  
            "pathId":44,
            "time":-105220820.7,
            "label":"MSN"
         }
      ],
      "effectiveness":1.62
   },
   {  
      "roi":2.12,
      "pathCount":37316,
      "impressionPerNode":7.01,
      "conversionRate":0.014,
      "pathId":45,
      "nodes":[  
         {  
            "pathId":45,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":45,
            "time":78.6,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.1
   },
   {  
      "roi":3.1,
      "pathCount":937820,
      "impressionPerNode":7.71,
      "conversionRate":0.0,
      "pathId":46,
      "nodes":[  
         {  
            "pathId":46,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":46,
            "time":464.1,
            "label":"Buzzfeed"
         },
         {  
            "pathId":46,
            "time":-8885.3,
            "label":"NYTimes"
         },
         {  
            "pathId":46,
            "time":4458.0,
            "label":"MSN"
         },
         {  
            "pathId":46,
            "time":-64062.3,
            "label":"ESPN2"
         },
         {  
            "pathId":46,
            "time":532486.8,
            "label":""
         },
         {  
            "pathId":46,
            "time":-2626796.5,
            "label":"ESPN2"
         },
         {  
            "pathId":46,
            "time":53630084.4,
            "label":"MSN"
         }
      ],
      "effectiveness":0.98
   },
   {  
      "roi":0.18,
      "pathCount":1560542,
      "impressionPerNode":6.43,
      "conversionRate":0.023,
      "pathId":47,
      "nodes":[  
         {  
            "pathId":47,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":47,
            "time":18.8,
            "label":"YouTube"
         },
         {  
            "pathId":47,
            "time":170.7,
            "label":"ESPN2"
         },
         {  
            "pathId":47,
            "time":-2587.7,
            "label":""
         },
         {  
            "pathId":47,
            "time":46068.7,
            "label":""
         },
         {  
            "pathId":47,
            "time":-808999.2,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":2.28
   },
   {  
      "roi":3.35,
      "pathCount":598478,
      "impressionPerNode":7.28,
      "conversionRate":0.074,
      "pathId":48,
      "nodes":[  
         {  
            "pathId":48,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":48,
            "time":605.0,
            "label":"MSN"
         },
         {  
            "pathId":48,
            "time":-6947.6,
            "label":"NYTimes"
         },
         {  
            "pathId":48,
            "time":76161.5,
            "label":"NYTimes"
         },
         {  
            "pathId":48,
            "time":-1042119.3,
            "label":"Yahoo"
         }
      ],
      "effectiveness":0.86
   },
   {  
      "roi":3.48,
      "pathCount":4919451,
      "impressionPerNode":7.32,
      "conversionRate":0.013,
      "pathId":49,
      "nodes":[  
         {  
            "pathId":49,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":49,
            "time":93.9,
            "label":"YouTube"
         },
         {  
            "pathId":49,
            "time":-167.6,
            "label":"NYTimes"
         },
         {  
            "pathId":49,
            "time":2797.6,
            "label":"YouTube"
         },
         {  
            "pathId":49,
            "time":-22843.2,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.53
   },
   {  
      "roi":0.78,
      "pathCount":2080482,
      "impressionPerNode":6.74,
      "conversionRate":0.052,
      "pathId":50,
      "nodes":[  
         {  
            "pathId":50,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":50,
            "time":384.6,
            "label":""
         },
         {  
            "pathId":50,
            "time":-3128.7,
            "label":"YouTube"
         },
         {  
            "pathId":50,
            "time":-3079.7,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.82
   },
   {  
      "roi":0.03,
      "pathCount":853606,
      "impressionPerNode":6.44,
      "conversionRate":0.016,
      "pathId":51,
      "nodes":[  
         {  
            "pathId":51,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":51,
            "time":253.5,
            "label":"Buzzfeed"
         },
         {  
            "pathId":51,
            "time":-928.2,
            "label":"ESPN2"
         },
         {  
            "pathId":51,
            "time":4670.0,
            "label":"ESPN2"
         },
         {  
            "pathId":51,
            "time":-30946.2,
            "label":"YouTube"
         },
         {  
            "pathId":51,
            "time":101789.5,
            "label":""
         }
      ],
      "effectiveness":0.01
   },
   {  
      "roi":2.23,
      "pathCount":1974193,
      "impressionPerNode":3.51,
      "conversionRate":0.072,
      "pathId":52,
      "nodes":[  
         {  
            "pathId":52,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.44
   },
   {  
      "roi":1.17,
      "pathCount":1891256,
      "impressionPerNode":5.46,
      "conversionRate":0.006,
      "pathId":53,
      "nodes":[  
         {  
            "pathId":53,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":53,
            "time":568.5,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.52
   },
   {  
      "roi":0.12,
      "pathCount":2666017,
      "impressionPerNode":6.43,
      "conversionRate":0.021,
      "pathId":54,
      "nodes":[  
         {  
            "pathId":54,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":54,
            "time":70.8,
            "label":"YouTube"
         },
         {  
            "pathId":54,
            "time":-860.7,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.68
   },
   {  
      "roi":0.37,
      "pathCount":293049,
      "impressionPerNode":6.35,
      "conversionRate":0.015,
      "pathId":55,
      "nodes":[  
         {  
            "pathId":55,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":55,
            "time":8.6,
            "label":"Yahoo"
         },
         {  
            "pathId":55,
            "time":290.4,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.92
   },
   {  
      "roi":0.47,
      "pathCount":690636,
      "impressionPerNode":5.58,
      "conversionRate":0.015,
      "pathId":56,
      "nodes":[  
         {  
            "pathId":56,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":56,
            "time":53.5,
            "label":"Yahoo"
         },
         {  
            "pathId":56,
            "time":-403.9,
            "label":"ESPN2"
         },
         {  
            "pathId":56,
            "time":2966.8,
            "label":"eBay"
         },
         {  
            "pathId":56,
            "time":761.2,
            "label":"MSN"
         }
      ],
      "effectiveness":1.55
   },
   {  
      "roi":1.22,
      "pathCount":1551374,
      "impressionPerNode":2.43,
      "conversionRate":0.02,
      "pathId":57,
      "nodes":[  
         {  
            "pathId":57,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":57,
            "time":404.8,
            "label":"NYTimes"
         },
         {  
            "pathId":57,
            "time":-8722.4,
            "label":"ESPN2"
         },
         {  
            "pathId":57,
            "time":150138.3,
            "label":"eBay"
         },
         {  
            "pathId":57,
            "time":-4020664.1,
            "label":"MSN"
         }
      ],
      "effectiveness":0.13
   },
   {  
      "roi":0.75,
      "pathCount":2881935,
      "impressionPerNode":4.01,
      "conversionRate":0.002,
      "pathId":58,
      "nodes":[  
         {  
            "pathId":58,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":2.24
   },
   {  
      "roi":3.14,
      "pathCount":495831,
      "impressionPerNode":4.85,
      "conversionRate":0.012,
      "pathId":59,
      "nodes":[  
         {  
            "pathId":59,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":59,
            "time":70.3,
            "label":"MSN"
         },
         {  
            "pathId":59,
            "time":-131.2,
            "label":"ESPN2"
         },
         {  
            "pathId":59,
            "time":3932.3,
            "label":"Yahoo"
         },
         {  
            "pathId":59,
            "time":-36055.9,
            "label":"eBay"
         },
         {  
            "pathId":59,
            "time":679383.2,
            "label":"eBay"
         }
      ],
      "effectiveness":1.65
   },
   {  
      "roi":2.66,
      "pathCount":2459127,
      "impressionPerNode":5.83,
      "conversionRate":0.016,
      "pathId":60,
      "nodes":[  
         {  
            "pathId":60,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":60,
            "time":711.7,
            "label":"ESPN2"
         },
         {  
            "pathId":60,
            "time":-5200.1,
            "label":"YouTube"
         },
         {  
            "pathId":60,
            "time":22410.9,
            "label":"YouTube"
         },
         {  
            "pathId":60,
            "time":-307842.7,
            "label":"Yahoo"
         },
         {  
            "pathId":60,
            "time":329777.7,
            "label":"YouTube"
         },
         {  
            "pathId":60,
            "time":-1205780.7,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.17
   },
   {  
      "roi":1.23,
      "pathCount":7896517,
      "impressionPerNode":3.65,
      "conversionRate":0.012,
      "pathId":61,
      "nodes":[  
         {  
            "pathId":61,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":61,
            "time":786.3,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.14
   },
   {  
      "roi":0.09,
      "pathCount":3917625,
      "impressionPerNode":3.04,
      "conversionRate":0.006,
      "pathId":62,
      "nodes":[  
         {  
            "pathId":62,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":1.43
   },
   {  
      "roi":0.86,
      "pathCount":577263,
      "impressionPerNode":2.12,
      "conversionRate":0.025,
      "pathId":63,
      "nodes":[  
         {  
            "pathId":63,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":63,
            "time":187.5,
            "label":"Yahoo"
         }
      ],
      "effectiveness":0.01
   },
   {  
      "roi":4.31,
      "pathCount":1768079,
      "impressionPerNode":3.93,
      "conversionRate":0.077,
      "pathId":64,
      "nodes":[  
         {  
            "pathId":64,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":64,
            "time":131.6,
            "label":""
         },
         {  
            "pathId":64,
            "time":-2459.2,
            "label":"YouTube"
         },
         {  
            "pathId":64,
            "time":44712.6,
            "label":"Buzzfeed"
         },
         {  
            "pathId":64,
            "time":-1021481.8,
            "label":"MSN"
         }
      ],
      "effectiveness":0.27
   },
   {  
      "roi":0.53,
      "pathCount":1529652,
      "impressionPerNode":5.46,
      "conversionRate":0.011,
      "pathId":65,
      "nodes":[  
         {  
            "pathId":65,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":65,
            "time":639.6,
            "label":""
         }
      ],
      "effectiveness":0.04
   },
   {  
      "roi":1.42,
      "pathCount":440254,
      "impressionPerNode":7.06,
      "conversionRate":0.023,
      "pathId":66,
      "nodes":[  
         {  
            "pathId":66,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":66,
            "time":862.1,
            "label":"eBay"
         },
         {  
            "pathId":66,
            "time":-8024.4,
            "label":"MSN"
         },
         {  
            "pathId":66,
            "time":55696.0,
            "label":"eBay"
         },
         {  
            "pathId":66,
            "time":-747523.9,
            "label":"eBay"
         },
         {  
            "pathId":66,
            "time":8346620.3,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.75
   },
   {  
      "roi":1.03,
      "pathCount":3320239,
      "impressionPerNode":5.81,
      "conversionRate":0.01,
      "pathId":67,
      "nodes":[  
         {  
            "pathId":67,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":67,
            "time":730.8,
            "label":"MSN"
         },
         {  
            "pathId":67,
            "time":-15078.6,
            "label":"YouTube"
         },
         {  
            "pathId":67,
            "time":382069.7,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.8
   },
   {  
      "roi":1.83,
      "pathCount":1023462,
      "impressionPerNode":4.94,
      "conversionRate":0.004,
      "pathId":68,
      "nodes":[  
         {  
            "pathId":68,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":68,
            "time":28.5,
            "label":"eBay"
         },
         {  
            "pathId":68,
            "time":-5.3,
            "label":"YouTube"
         },
         {  
            "pathId":68,
            "time":31.7,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.27
   },
   {  
      "roi":0.19,
      "pathCount":3176759,
      "impressionPerNode":7.86,
      "conversionRate":0.019,
      "pathId":69,
      "nodes":[  
         {  
            "pathId":69,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.18
   },
   {  
      "roi":0.76,
      "pathCount":602246,
      "impressionPerNode":4.24,
      "conversionRate":0.008,
      "pathId":70,
      "nodes":[  
         {  
            "pathId":70,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":70,
            "time":209.8,
            "label":"NYTimes"
         },
         {  
            "pathId":70,
            "time":-5266.9,
            "label":"Yahoo"
         },
         {  
            "pathId":70,
            "time":40689.2,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.73
   },
   {  
      "roi":2.19,
      "pathCount":1775731,
      "impressionPerNode":1.48,
      "conversionRate":0.05,
      "pathId":71,
      "nodes":[  
         {  
            "pathId":71,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":71,
            "time":215.4,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":1.32
   },
   {  
      "roi":2.89,
      "pathCount":2277791,
      "impressionPerNode":1.34,
      "conversionRate":0.037,
      "pathId":72,
      "nodes":[  
         {  
            "pathId":72,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":72,
            "time":405.7,
            "label":"MSN"
         },
         {  
            "pathId":72,
            "time":-12173.5,
            "label":"MSN"
         },
         {  
            "pathId":72,
            "time":116672.2,
            "label":"ESPN2"
         },
         {  
            "pathId":72,
            "time":-2404186.8,
            "label":"eBay"
         },
         {  
            "pathId":72,
            "time":61496720.3,
            "label":"MSN"
         },
         {  
            "pathId":72,
            "time":-1167263035.3,
            "label":"eBay"
         },
         {  
            "pathId":72,
            "time":10091354874.6,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":1.88
   },
   {  
      "roi":1.82,
      "pathCount":2304002,
      "impressionPerNode":5.74,
      "conversionRate":0.019,
      "pathId":73,
      "nodes":[  
         {  
            "pathId":73,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":73,
            "time":81.2,
            "label":"Buzzfeed"
         },
         {  
            "pathId":73,
            "time":-9.4,
            "label":"MSN"
         },
         {  
            "pathId":73,
            "time":379.7,
            "label":""
         }
      ],
      "effectiveness":1.04
   },
   {  
      "roi":0.08,
      "pathCount":1473414,
      "impressionPerNode":4.68,
      "conversionRate":0.006,
      "pathId":74,
      "nodes":[  
         {  
            "pathId":74,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":74,
            "time":76.0,
            "label":"NYTimes"
         },
         {  
            "pathId":74,
            "time":-530.4,
            "label":"Yahoo"
         },
         {  
            "pathId":74,
            "time":6130.5,
            "label":"MSN"
         },
         {  
            "pathId":74,
            "time":-185633.8,
            "label":"ESPN2"
         },
         {  
            "pathId":74,
            "time":3154039.7,
            "label":"NYTimes"
         },
         {  
            "pathId":74,
            "time":-106396418.9,
            "label":"ESPN2"
         },
         {  
            "pathId":74,
            "time":3272163607.8,
            "label":"eBay"
         }
      ],
      "effectiveness":0.57
   },
   {  
      "roi":2.8,
      "pathCount":4831007,
      "impressionPerNode":4.28,
      "conversionRate":0.005,
      "pathId":75,
      "nodes":[  
         {  
            "pathId":75,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":75,
            "time":873.8,
            "label":"Buzzfeed"
         },
         {  
            "pathId":75,
            "time":-4304.5,
            "label":"Yahoo"
         },
         {  
            "pathId":75,
            "time":19281.1,
            "label":"Yahoo"
         },
         {  
            "pathId":75,
            "time":-623478.8,
            "label":"MSN"
         }
      ],
      "effectiveness":1.73
   },
   {  
      "roi":0.59,
      "pathCount":802804,
      "impressionPerNode":6.6,
      "conversionRate":0.003,
      "pathId":76,
      "nodes":[  
         {  
            "pathId":76,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":76,
            "time":766.8,
            "label":""
         },
         {  
            "pathId":76,
            "time":-14022.6,
            "label":"eBay"
         },
         {  
            "pathId":76,
            "time":436539.6,
            "label":"MSN"
         },
         {  
            "pathId":76,
            "time":-12320632.4,
            "label":"eBay"
         }
      ],
      "effectiveness":0.77
   },
   {  
      "roi":3.12,
      "pathCount":5365393,
      "impressionPerNode":4.79,
      "conversionRate":0.066,
      "pathId":77,
      "nodes":[  
         {  
            "pathId":77,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":77,
            "time":720.3,
            "label":"eBay"
         },
         {  
            "pathId":77,
            "time":-25282.9,
            "label":"ESPN2"
         },
         {  
            "pathId":77,
            "time":638397.4,
            "label":"NYTimes"
         }
      ],
      "effectiveness":0.97
   },
   {  
      "roi":0.57,
      "pathCount":4013504,
      "impressionPerNode":7.33,
      "conversionRate":0.031,
      "pathId":78,
      "nodes":[  
         {  
            "pathId":78,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":78,
            "time":449.5,
            "label":"NYTimes"
         },
         {  
            "pathId":78,
            "time":-5866.5,
            "label":"Yahoo"
         },
         {  
            "pathId":78,
            "time":70425.6,
            "label":"YouTube"
         },
         {  
            "pathId":78,
            "time":-730674.0,
            "label":"YouTube"
         },
         {  
            "pathId":78,
            "time":18771424.2,
            "label":"MSN"
         },
         {  
            "pathId":78,
            "time":-266380432.2,
            "label":"eBay"
         },
         {  
            "pathId":78,
            "time":1397662836.2,
            "label":"Yahoo"
         }
      ],
      "effectiveness":0.05
   },
   {  
      "roi":1.08,
      "pathCount":6007978,
      "impressionPerNode":3.76,
      "conversionRate":0.011,
      "pathId":79,
      "nodes":[  
         {  
            "pathId":79,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":1.42
   },
   {  
      "roi":0.19,
      "pathCount":81098,
      "impressionPerNode":3.11,
      "conversionRate":0.065,
      "pathId":80,
      "nodes":[  
         {  
            "pathId":80,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":80,
            "time":456.3,
            "label":"Buzzfeed"
         },
         {  
            "pathId":80,
            "time":-11645.4,
            "label":"YouTube"
         },
         {  
            "pathId":80,
            "time":161261.5,
            "label":"eBay"
         },
         {  
            "pathId":80,
            "time":-6271709.0,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.72
   },
   {  
      "roi":0.11,
      "pathCount":1916635,
      "impressionPerNode":3.85,
      "conversionRate":0.016,
      "pathId":81,
      "nodes":[  
         {  
            "pathId":81,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":81,
            "time":383.6,
            "label":"Buzzfeed"
         },
         {  
            "pathId":81,
            "time":-13549.0,
            "label":"Yahoo"
         },
         {  
            "pathId":81,
            "time":281132.0,
            "label":""
         },
         {  
            "pathId":81,
            "time":-5155170.0,
            "label":"YouTube"
         },
         {  
            "pathId":81,
            "time":70158304.3,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.44
   },
   {  
      "roi":3.96,
      "pathCount":2212665,
      "impressionPerNode":3.05,
      "conversionRate":0.019,
      "pathId":82,
      "nodes":[  
         {  
            "pathId":82,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":82,
            "time":755.8,
            "label":""
         },
         {  
            "pathId":82,
            "time":-2501.0,
            "label":"YouTube"
         },
         {  
            "pathId":82,
            "time":69213.5,
            "label":"eBay"
         },
         {  
            "pathId":82,
            "time":-1379852.5,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.24
   },
   {  
      "roi":2.3,
      "pathCount":46683,
      "impressionPerNode":7.42,
      "conversionRate":0.0,
      "pathId":83,
      "nodes":[  
         {  
            "pathId":83,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":83,
            "time":942.1,
            "label":"Buzzfeed"
         },
         {  
            "pathId":83,
            "time":-15125.7,
            "label":""
         },
         {  
            "pathId":83,
            "time":596179.8,
            "label":"eBay"
         },
         {  
            "pathId":83,
            "time":-20012907.7,
            "label":"ESPN2"
         },
         {  
            "pathId":83,
            "time":437075333.0,
            "label":"YouTube"
         },
         {  
            "pathId":83,
            "time":-14784436003.6,
            "label":"YouTube"
         }
      ],
      "effectiveness":1.6
   },
   {  
      "roi":1.9,
      "pathCount":1516790,
      "impressionPerNode":7.59,
      "conversionRate":0.05,
      "pathId":84,
      "nodes":[  
         {  
            "pathId":84,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":84,
            "time":719.9,
            "label":"YouTube"
         },
         {  
            "pathId":84,
            "time":-11260.5,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.38
   },
   {  
      "roi":0.22,
      "pathCount":3644559,
      "impressionPerNode":4.66,
      "conversionRate":0.014,
      "pathId":85,
      "nodes":[  
         {  
            "pathId":85,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":85,
            "time":7.1,
            "label":"NYTimes"
         },
         {  
            "pathId":85,
            "time":485.9,
            "label":"NYTimes"
         },
         {  
            "pathId":85,
            "time":-10911.7,
            "label":"ESPN2"
         },
         {  
            "pathId":85,
            "time":441557.9,
            "label":""
         }
      ],
      "effectiveness":1.7
   },
   {  
      "roi":1.65,
      "pathCount":232213,
      "impressionPerNode":6.45,
      "conversionRate":0.03,
      "pathId":86,
      "nodes":[  
         {  
            "pathId":86,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":86,
            "time":1061.8,
            "label":"ESPN2"
         },
         {  
            "pathId":86,
            "time":-33994.9,
            "label":"Yahoo"
         },
         {  
            "pathId":86,
            "time":125143.8,
            "label":""
         }
      ],
      "effectiveness":1.31
   },
   {  
      "roi":1.08,
      "pathCount":238061,
      "impressionPerNode":5.05,
      "conversionRate":0.0,
      "pathId":87,
      "nodes":[  
         {  
            "pathId":87,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":87,
            "time":629.6,
            "label":"YouTube"
         }
      ],
      "effectiveness":0.52
   },
   {  
      "roi":0.1,
      "pathCount":873656,
      "impressionPerNode":7.61,
      "conversionRate":0.015,
      "pathId":88,
      "nodes":[  
         {  
            "pathId":88,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":88,
            "time":533.1,
            "label":"eBay"
         },
         {  
            "pathId":88,
            "time":-20420.6,
            "label":"Buzzfeed"
         },
         {  
            "pathId":88,
            "time":703423.7,
            "label":"eBay"
         },
         {  
            "pathId":88,
            "time":-6166697.7,
            "label":"MSN"
         }
      ],
      "effectiveness":2.07
   },
   {  
      "roi":0.84,
      "pathCount":6527423,
      "impressionPerNode":3.9,
      "conversionRate":0.006,
      "pathId":89,
      "nodes":[  
         {  
            "pathId":89,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":89,
            "time":351.5,
            "label":"MSN"
         },
         {  
            "pathId":89,
            "time":-9892.8,
            "label":"YouTube"
         },
         {  
            "pathId":89,
            "time":103171.6,
            "label":"ESPN2"
         },
         {  
            "pathId":89,
            "time":-3144603.6,
            "label":"YouTube"
         },
         {  
            "pathId":89,
            "time":-2629028.3,
            "label":"YouTube"
         },
         {  
            "pathId":89,
            "time":89551931.4,
            "label":"Yahoo"
         }
      ],
      "effectiveness":2.12
   },
   {  
      "roi":0.12,
      "pathCount":4657352,
      "impressionPerNode":7.38,
      "conversionRate":0.081,
      "pathId":90,
      "nodes":[  
         {  
            "pathId":90,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.55
   },
   {  
      "roi":0.04,
      "pathCount":473781,
      "impressionPerNode":5.49,
      "conversionRate":0.008,
      "pathId":91,
      "nodes":[  
         {  
            "pathId":91,
            "time":0,
            "label":"purchase"
         }
      ],
      "effectiveness":0.06
   },
   {  
      "roi":0.43,
      "pathCount":4836819,
      "impressionPerNode":5.54,
      "conversionRate":0.022,
      "pathId":92,
      "nodes":[  
         {  
            "pathId":92,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":92,
            "time":352.1,
            "label":""
         },
         {  
            "pathId":92,
            "time":-13596.8,
            "label":"ESPN2"
         },
         {  
            "pathId":92,
            "time":156379.4,
            "label":"ESPN2"
         },
         {  
            "pathId":92,
            "time":-6350508.1,
            "label":""
         }
      ],
      "effectiveness":0.39
   },
   {  
      "roi":2.21,
      "pathCount":253462,
      "impressionPerNode":4.3,
      "conversionRate":0.004,
      "pathId":93,
      "nodes":[  
         {  
            "pathId":93,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":93,
            "time":183.8,
            "label":"Yahoo"
         },
         {  
            "pathId":93,
            "time":-880.7,
            "label":"eBay"
         },
         {  
            "pathId":93,
            "time":21034.6,
            "label":""
         },
         {  
            "pathId":93,
            "time":-51204.8,
            "label":"Yahoo"
         },
         {  
            "pathId":93,
            "time":644842.5,
            "label":""
         },
         {  
            "pathId":93,
            "time":-3115367.1,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.77
   },
   {  
      "roi":0.96,
      "pathCount":1532316,
      "impressionPerNode":7.26,
      "conversionRate":0.027,
      "pathId":94,
      "nodes":[  
         {  
            "pathId":94,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":94,
            "time":887.2,
            "label":"ESPN2"
         },
         {  
            "pathId":94,
            "time":-24187.4,
            "label":"Yahoo"
         },
         {  
            "pathId":94,
            "time":870954.4,
            "label":"NYTimes"
         },
         {  
            "pathId":94,
            "time":-37153590.0,
            "label":"MSN"
         },
         {  
            "pathId":94,
            "time":1522486471.8,
            "label":"Yahoo"
         },
         {  
            "pathId":94,
            "time":-48156543927.0,
            "label":"eBay"
         }
      ],
      "effectiveness":1.93
   },
   {  
      "roi":1.16,
      "pathCount":336356,
      "impressionPerNode":2.02,
      "conversionRate":0.014,
      "pathId":95,
      "nodes":[  
         {  
            "pathId":95,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":95,
            "time":26.8,
            "label":"ESPN2"
         }
      ],
      "effectiveness":0.8
   },
   {  
      "roi":1.39,
      "pathCount":21592,
      "impressionPerNode":7.97,
      "conversionRate":0.052,
      "pathId":96,
      "nodes":[  
         {  
            "pathId":96,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":96,
            "time":617.0,
            "label":"MSN"
         },
         {  
            "pathId":96,
            "time":-7170.4,
            "label":"MSN"
         },
         {  
            "pathId":96,
            "time":256331.8,
            "label":""
         },
         {  
            "pathId":96,
            "time":-4432426.2,
            "label":"Yahoo"
         },
         {  
            "pathId":96,
            "time":17168288.0,
            "label":""
         }
      ],
      "effectiveness":0.02
   },
   {  
      "roi":1.49,
      "pathCount":5404155,
      "impressionPerNode":7.96,
      "conversionRate":0.035,
      "pathId":97,
      "nodes":[  
         {  
            "pathId":97,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":97,
            "time":1117.3,
            "label":"Buzzfeed"
         },
         {  
            "pathId":97,
            "time":-28762.6,
            "label":"ESPN2"
         },
         {  
            "pathId":97,
            "time":1035637.9,
            "label":"Yahoo"
         },
         {  
            "pathId":97,
            "time":-2486097.5,
            "label":"eBay"
         },
         {  
            "pathId":97,
            "time":59998239.7,
            "label":"YouTube"
         }
      ],
      "effectiveness":1.37
   },
   {  
      "roi":0.03,
      "pathCount":3117497,
      "impressionPerNode":5.86,
      "conversionRate":0.034,
      "pathId":98,
      "nodes":[  
         {  
            "pathId":98,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":98,
            "time":1118.1,
            "label":"YouTube"
         },
         {  
            "pathId":98,
            "time":-24251.4,
            "label":"YouTube"
         },
         {  
            "pathId":98,
            "time":930536.5,
            "label":"NYTimes"
         },
         {  
            "pathId":98,
            "time":-17424875.1,
            "label":"Buzzfeed"
         }
      ],
      "effectiveness":0.71
   },
   {  
      "roi":0.05,
      "pathCount":4750168,
      "impressionPerNode":6.98,
      "conversionRate":0.051,
      "pathId":99,
      "nodes":[  
         {  
            "pathId":99,
            "time":0,
            "label":"purchase"
         },
         {  
            "pathId":99,
            "time":978.4,
            "label":"ESPN2"
         },
         {  
            "pathId":99,
            "time":-12381.6,
            "label":"Yahoo"
         },
         {  
            "pathId":99,
            "time":48568.2,
            "label":"eBay"
         },
         {  
            "pathId":99,
            "time":-1309976.4,
            "label":"MSN"
         },
         {  
            "pathId":99,
            "time":27704204.1,
            "label":"Yahoo"
         }
      ],
      "effectiveness":0.91
   }
];